# Generated by Django 3.2.14 on 2022-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='photos/profile/avatar_10.png', null=True, upload_to='photos/profile'),
        ),
    ]
